
server:
  port: 8082
spring:
  application:
    name: hrms-erp-ui
#
url-header: http

cors:
  allowed:
    origins: '*'
    methods: '*'
  exposed:
    headers: Access-Control-Allow-Origin, Content-Disposition, Access-Control-Expose-Headers,Access-Control-Allow-Headers,Access-Control-Allow-Credentials

log.level: info
log.file:  hrms-erp-ui.log
app.name:  hrms-erp-ui
app.version: @project.version@
log.pattern: EVENTTIME=%d{"yyyy-MM-dd HH:mm:ss.SSSXXX", UTC},LEVEL=%level,APP_NAME=${APP_NAME},APP_VERSION=${APP_VERSION},Line=%line,DETAIL=Package:%logger{36}:%msg%n
log.path: logs

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
ui-properties:
  environment: LOCAL